-- Oracle SQL: budgets table
CREATE TABLE budgets (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  category VARCHAR2(100) NOT NULL,
  month VARCHAR2(7) NOT NULL, -- format YYYY-MM
  amount NUMBER(12,2) NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_budgets_users FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ensure a user can't create duplicate budget for same category+month
CREATE UNIQUE INDEX ux_budgets_user_category_month ON budgets(user_id, category, month);

-- Example query to compute total spent per category for a given user+month
-- (assumes `expenses` table with columns: user_id, amount, category, date)
-- replace DATE->TO_CHAR(date,'YYYY-MM') for your DB date format
-- SELECT e.category, SUM(e.amount) as total_spent
-- FROM expenses e
-- WHERE e.user_id = :userId
--   AND TO_CHAR(e.date,'YYYY-MM') = :month
-- GROUP BY e.category;
